In [3]:
import numpy as np
import pandas as pd

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arra=np.arange(0,9).reshape(3,3)
arra

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arra2=np.arange(0,12).reshape(3,4)
arra2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
np.dot(arra,arra2)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155]])

In [25]:
arra3=np.random.rand(9).reshape(3,3)
arra3

array([[0.59443582, 0.776311  , 0.82099768],
       [0.34578353, 0.81900189, 0.29566901],
       [0.16481273, 0.70949312, 0.21514351]])

In [21]:
arra4=np.random.rand(12).reshape(3,4)
arra4

array([[0.08952459, 0.15077622, 0.82825817, 0.02415157],
       [0.71858073, 0.78071317, 0.97320589, 0.05239698],
       [0.51490664, 0.03892827, 0.56356051, 0.605849  ]])

In [22]:
np.dot(arra3,arra4)

array([[1.09024105, 0.73226002, 1.72081543, 0.61282913],
       [0.58364548, 0.40806404, 0.84354377, 0.30156277],
       [0.96198916, 0.53949652, 1.19411168, 0.62458817]])